### ISSUE TITLE
Request for different game's character-like presets

### ISSUE THREAD

**Issue by ChichoRD** [Matthew-J-Spencer/Ultimate-2D-Controller#1]
Hi, I'm a subscriber of yours that just watched your video and had an idea to extend this repository.
As you showcased Celeste and Super Meat Boy are ones of the greatest games in terms of platforming and character controls. Wouldn't it be so nice for developers to achive nearly as much as these with your awesome 2D-controller?

I know that although the scripting and physics have already been solve, many developers could stugle with getting the right values for each of the many parameters in your Character Controller. Therefore why not taking the time among all who decide to use this solution, and those who find some cool values for your script parameters contribute with a preset file (the ones you can make in unity by presing the second button on the top right of any component) for this. It could have a Mario preset, a Celeste one, etc.

Please regard adding or creating these presets for your repository.

**Comment by Matthew-J-Spencer** [comment]
Great suggestion. I'll leave this open until I get around to it.

**Comment by Tymski** [comment]
I would suggest to not implement this feature as Unity Presets because they are in the Editor namespace. Instead use a scriptable object with settings that could be Applied to the controller both in editor and in runtime. This would allow to dynamically swap between the presets during gameplay for quicker testing and iteration.

**Comment by Matthew-J-Spencer** [comment]
I won't be extending this version further.
