### ISSUE TITLE
Many console errors after importing prefab

### ISSUE THREAD

**Issue by JoshS-dev** [Matthew-J-Spencer/Ultimate-2D-Controller#14]
On importing the file under Prefabs, the following errors appear in the console. 

![Unity_ihtg8UEKQI](https://user-images.githubusercontent.com/34352316/181071394-dd27efe3-088b-4e86-975a-a79507535e83.png)

**Comment by TeoSapo** [comment]
This is because you import the Scripts folder and also import all the "Tarodev 2d controller" that also has a Scripts folder and is like overlapping the same scripts over and over. Just import only the "Tarodev 2d controller" and keep the scripts that came with that folder. You only need the 3 scripts that are in that package

**Comment by zaidmermam** [comment]
if you are still interested, checking my ignored pull request might help

**Comment by TeoSapo** [comment]
I’m sorry, i don’t understand the meaning of this email. Could you explain
it to me?

Thanks.

**Comment by Matthew-J-Spencer** [comment]
Thanks [zaidmermam](https://github.com/zaidmermam)~

I've also upgraded the free source with a more resilient version.
